# QOS Auto-Filler configuration
# Use relative paths to keep it portable across systems.

section: all
extractor_backend: pymupdf

template_docx: 'D:\JB Pharma internal\JB Pharma\Tagging- mapping logic\Tagging- mapping logic\Quality Overall Summary.docx'
dossier_root: 'D:\JB Pharma internal\JB Pharma\Cardiolek'
filled_reference_docx: 'D:\JB Pharma internal\JB Pharma\Filled Template\Filled Template\Quality Overall Summary_QOS.docx'
output_docx: 'D:\JB Pharma internal\JB Pharma\Cardiolek\Output\Quality Overall Summary_QOS_2.3.S.1_Auto.docx'
artifacts_dir: 'D:\JB Pharma internal\JB Pharma\Cardiolek\Output\logger'
